### ISSUE TITLE
X86运行后报错

### ISSUE THREAD

**Issue by cxw3292008** [xxxxue/war3-72bian#1]
Unable to cast COM object of type 'System.__ComObject' to interface type 'Idmsoft'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{F3F54BC2-D6D1-4A85-B943-16287ECEA64C}' failed due to the following error: 不支持此接口 (0x80004002 (E_NOINTERFACE)).

**Comment by xxxxue** [comment]
想要改游戏有更简单的方法，
直接用CE 锁定 宝箱的数量，无限开宝箱，
也可以 去锁定 具体宝石的数量，无限用宝石，

也可以 去刷存档(有几率封号)， 立刻装备毕业，
装备和强化等级不能弄得太多。

这个图游戏开始有一个算法，
检测你 地图等级和总装备与强化等级 之间的关系。

地图等级15只能 毕业三四个角色。

魔兽其他的图也一样，用CE搜就行。
数值随便改，都不封号。

不过这样游戏就没啥意思了，
自从改过游戏存档后，就没玩这个图了，
魔兽争霸也戒了。

**Comment by cxw3292008** [comment]
是的，改游戏就没意思了，我主要是对这个模拟操作自动去刷boss感兴趣，魔兽的图凉的也快。
